version: '3'
services:
  wallet-api:
    image: "io.hugo/apps/web-api"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - wallet-postgres
  wallet-postgres:
    image: "postgres:14-alpine"
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=postgres
