version: '3'
services:
  wallet-sync-api:
    image: app-web-sync-api:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - wallet-postgres
  wallet-api:
    image: app-web-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - wallet-postgres
  wallet-postgres:
    image: "postgres:14-alpine"
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./benchmark/prometheus:/etc/prometheus/
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./benchmark/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  influxdb:
    image: influxdb:1.7.4
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
