apiVersion: 1

datasources:
  - name: K6InfluxDB
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: true
  - name: InfluxDB_GIT
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token:  $INFLUXDB_API_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_DEFAULT_BUCKET
      tlsSkipVerify: true
      timeout: 600
  - name: SpringPrometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
