apiVersion: 1

datasources:
  - name: K6InfluxDB
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: true
  - name: SpringPrometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
