spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    org.hibernate.SQL: debug

elide:
  json-api:
    path: /json
    enabled: true
  swagger:
    path: /doc
    enabled: true
  graphql:
    enabled: true
    path: /graphql/api
    subscription:
      enabled: true
      path: /subscription
