spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres


management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
